### ISSUE TITLE
How do I setup a random port for the embedded mongo instance for this

### ISSUE THREAD

**Issue by ljramones** [michael-simons/datamongotest-autoconfigure-spring-boot#1]
I noted that when I have mongo running in the background while I used the embedded test, the test will fail with an address in use (port 27017).

Is there a way to set the embedded database to use a different port and have this work?

I can stop my mongo instance and it will work but ...

**Comment by michael-simons** [comment]
Hi,
thanks for asking! This project made it into Spring Boot itself, the project is obsolete since Spring Boot 1.5


Here's the link to the reference documentation: [Auto-configured Data MongoDB tests](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-autoconfigured-mongo-test)

You have two options:

1. Random port for embedded mongo (only has an effect when on the path): No action needed on Spring Boot 1.5 (see https://github.com/spring-projects/spring-boot/issues/8044) , or if you are on 1.4.x and below, `spring.data.mongodb.port=0 `
1. Disable the auto configuration of embedded mongo while using `DataMongoTest`like this:

```
import org.junit.runner.RunWith;
import org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration;
import org.springframework.boot.test.autoconfigure.data.mongo.DataMongoTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@DataMongoTest(excludeAutoConfiguration = EmbeddedMongoAutoConfiguration.class)
public class ExampleDataMongoNonEmbeddedTests {
}
```

If you want to use this project right here with Boot 1.4, then you set the port to 0 like show above or just don't put embedded mongo on the path.
